// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxvbwiNCZyVbzE53LnezAjws4-Fsiv7Zo',
    appId: '1:687096179426:android:4c90e12d6a5ab640abccbb',
    messagingSenderId: '687096179426',
    projectId: 'todo-list-provider-20994',
    storageBucket: 'todo-list-provider-20994.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGiHsnumJ8wtN_bSSnjiU_RG_d6iUu0nM',
    appId: '1:687096179426:ios:aa2b925e1cf84754abccbb',
    messagingSenderId: '687096179426',
    projectId: 'todo-list-provider-20994',
    storageBucket: 'todo-list-provider-20994.firebasestorage.app',
    androidClientId: '687096179426-cp41uepfv4uva299kingtnmauvseovv6.apps.googleusercontent.com',
    iosClientId: '687096179426-mmjan0mvsughilehl44vtfihnbo9gb45.apps.googleusercontent.com',
    iosBundleId: 'br.com.diego.todoListApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0na-mMhPuwksj35CeuU3SEpMobmE9WOk',
    appId: '1:687096179426:web:f630910b329b1575abccbb',
    messagingSenderId: '687096179426',
    projectId: 'todo-list-provider-20994',
    authDomain: 'todo-list-provider-20994.firebaseapp.com',
    storageBucket: 'todo-list-provider-20994.firebasestorage.app',
    measurementId: 'G-GF2PTYXFZ8',
  );

}